import { BenhSu, listPatient } from "./model";

export const LISTPATIENT: listPatient[] = [
  {
    maBenhNhan: "ATKV01",
    clientName: "AN THỊ KHÁNH VÂN",
    namSinh: 1993,
    dienThoai: "0336475713",
    gioiTinh: "Nam",
    canNang: 65,
    chieuCao: 163,
    email: "ximvhs26092002@gmail.com",
    address: "254/98/9E Âu Cơ, Phường 9, Q. Tân Bình, TP. Hồ Chí Minh",
  },
  {
    maBenhNhan: "ATKV02",
    clientName: "AN THỊ KHÁNH VÂN",
    namSinh: 1993,
    dienThoai: "0336475713",
    gioiTinh: "Nam",
    canNang: 65,
    chieuCao: 163,
    email: "ximvhs26092002@gmail.com",
    address: "254/98/9E Âu Cơ, Phường 9, Q. Tân Bình, TP. Hồ Chí Minh",
  },
];

// api:MD_BenhAn?maBenhNhan=ATKV01,
export const BENHSU: BenhSu = {
  address: "Binh Thanh",
  bankAccount: null,
  benhAns: [
    {
      benhAnId: 12428,
      chiTiet: [
        {
          benhAnId: 12428,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48451,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "benhSu",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "Đau bụng, khó chịu",
        },
        {
          benhAnId: 12428,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48442,
          ketQua: "Ast: 27, alt: 32, choleterol: 3.6, Tryglycerid 2.2 HDL: 1.1",
          loai: "",
          loaiXetNghiem: "canLamSang",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "Huyết áp",
        },
        {
          benhAnId: 12428,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48444,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "chuanDoan",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "Bệnh án mới chưa có chuẩn đoán",
        },
        {
          benhAnId: 12428,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48445,
          ketQua: null,
          loai: "ghiChu",
          loaiXetNghiem: "khamLamSang",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: null,
        },
        {
          benhAnId: 12428,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48446,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "KhamMat",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: null,
        },
        {
          benhAnId: 12428,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48447,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "LoiDan",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "Uống thuốc, nghỉ ngơi đúng giờ",
        },
        {
          benhAnId: 12428,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48448,
          ketQua: "",
          loai: "",
          loaiXetNghiem: "NgayTaikham",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "2024-03-12T14:58:17.8",
        },
        {
          benhAnId: 12428,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48449,
          ketQua: "Trưa 1 liều, tối 1 liều, 1 ngày uống",
          loai: "",
          loaiXetNghiem: "thuocDieuTri",
          productId: 0,
          soLuong: 2,
          tenFile: null,
          tenXetNghiem: "Panadol",
        },
        {
          benhAnId: 12428,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48450,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "trieuChung",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "Đau đầu, khó chịu trong người",
        },
        {
          benhAnId: 12428,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48451,
          ketQua: "Không sao",
          loai: "",
          loaiXetNghiem: "xetNghiem",
          productId: 0,
          soLuong: 0,
          tenFile: "",
          tenXetNghiem: null,
        },
      ],
      chuanDoan: "Bị đau cổ vai gáy",
      customField1: null,
      customField2: null,
      customField3: null,
      maBenhNhan: "ATKV01",
      nextStep: null,
      ngay: "2024-04-12T14:58:17.8",
      soLuuTru: "BA002272",
      status: 0,
    },
    {
      benhAnId: 12429,
      chiTiet: [
        {
          benhAnId: 12429,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48453,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "benhSu",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "Đau ngực, khó thở kéo dài trong 3 ngày.",
        },
        {
          benhAnId: 12429,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48454,
          ketQua: "Thiếu máu cơ tim",
          loai: "",
          loaiXetNghiem: "canLamSang",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "Điện tâm đồ",
        },
        {
          benhAnId: 12429,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48455,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "chuanDoan",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "Bệnh án mới chưa có chuẩn đoán",
        },
        {
          benhAnId: 12429,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48456,
          ketQua: null,
          loai: "ghiChu",
          loaiXetNghiem: "khamLamSang",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: null,
        },
        {
          benhAnId: 12429,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48457,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "KhamMat",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: null,
        },
        {
          benhAnId: 12429,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48458,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "LoiDan",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "Uống thuốc đúng giờ",
        },
        {
          benhAnId: 12429,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48459,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "NgayTaikham",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "2024-03-12T14:58:17.8",
        },
        {
          benhAnId: 12429,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48460,
          ketQua: "trưa tối 1 liều",
          loai: "",
          loaiXetNghiem: "thuocDieuTri",
          productId: 0,
          soLuong: 2,
          tenFile: null,
          tenXetNghiem: "Nexium 40mg",
        },
        {
          benhAnId: 12429,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48461,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "trieuChung",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "Đau ngực, tức ngực, khó thở",
        },
        {
          benhAnId: 12429,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48462,
          ketQua: "Bình thường",
          loai: "",
          loaiXetNghiem: "xetNghiem",
          productId: 0,
          soLuong: 0,
          tenFile:
            "https://easterngroup.com.vn/uploads/d%E1%BB%8Bch_t%E1%BB%A7y_n%C3%A3o_2.jpg",
          tenXetNghiem: "Não",
        },
        {
          benhAnId: 12429,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48462,
          ketQua: "120/80mmHg",
          loai: "",
          loaiXetNghiem: "xetNghiem",
          productId: 0,
          soLuong: 0,
          tenFile:
            "https://easterngroup.com.vn/uploads/d%E1%BB%8Bch_t%E1%BB%A7y_n%C3%A3o_2.jpg",
          tenXetNghiem: "Huyết áp",
        },
        {
          benhAnId: 12429,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48462,
          ketQua: "67 lần/phút",
          loai: "",
          loaiXetNghiem: "xetNghiem",
          productId: 0,
          soLuong: 0,
          tenFile:
            "https://easterngroup.com.vn/uploads/d%E1%BB%8Bch_t%E1%BB%A7y_n%C3%A3o_2.jpg",
          tenXetNghiem: "Mạch",
        },
      ],
      chuanDoan: "Bệnh án mới chưa có đoán được",
      customField1: null,
      customField2: null,
      customField3: null,
      maBenhNhan: "ATKV01",
      nextStep: null,
      ngay: "2024-03-12T14:58:17.8",
      soLuuTru: "BA002273",
      status: 0,
    },
    {
      benhAnId: 12430,
      chiTiet: [
        {
          benhAnId: 12430,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48463,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "benhSu",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "Nhức đầu, cảm cúm",
        },
        {
          benhAnId: 12430,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48464,
          ketQua: "Không sao",
          loai: "",
          loaiXetNghiem: "canLamSang",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "Test3",
        },
        {
          benhAnId: 12430,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48465,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "chuanDoan",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "Bệnh án mới chưa có chuẩn đoán",
        },
        {
          benhAnId: 12430,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48466,
          ketQua: null,
          loai: "ghiChu",
          loaiXetNghiem: "khamLamSang",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: null,
        },
        {
          benhAnId: 12430,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48467,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "KhamMat",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: null,
        },
        {
          benhAnId: 12430,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48468,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "LoiDan",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: null,
        },
        {
          benhAnId: 12430,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48469,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "NgayTaikham",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "2024-03-12T14:58:17.8",
        },
        {
          benhAnId: 12430,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48470,
          ketQua: "Sáng, trưa, chiều 1 liều",
          loai: "",
          loaiXetNghiem: "thuocDieuTri",
          productId: 0,
          soLuong: 3,
          tenFile: null,
          tenXetNghiem: "Nexium 40mg",
        },
        {
          benhAnId: 12430,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48470,
          ketQua: "Sáng, trưa, chiều 1 liều",
          loai: "",
          loaiXetNghiem: "thuocDieuTri",
          productId: 0,
          soLuong: 2,
          tenFile: null,
          tenXetNghiem: "Notalium 10mh",
        },
        {
          benhAnId: 12430,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48470,
          ketQua: "Sáng, trưa, chiều 1 liều",
          loai: "",
          loaiXetNghiem: "thuocDieuTri",
          productId: 0,
          soLuong: 5,
          tenFile: null,
          tenXetNghiem: "Nexium 40mg",
        },
        {
          benhAnId: 12430,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48471,
          ketQua: null,
          loai: "",
          loaiXetNghiem: "trieuChung",
          productId: 0,
          soLuong: 0,
          tenFile: null,
          tenXetNghiem: "Mất ngủ, đau đầu",
        },
        {
          benhAnId: 12430,
          customField1: null,
          customField2: null,
          customField3: null,
          customField4: null,
          customField5: null,
          id: 48472,
          ketQua: "Không sao",
          loai: "",
          loaiXetNghiem: "xetNghiem",
          productId: 0,
          soLuong: 0,
          tenFile:
            "https://image.nhandan.vn/w800/Files/Images/2021/09/13/xet0nghiem_mau-1631521608723.jpg.webp",
          tenXetNghiem: "Máu",
        },
      ],
      chuanDoan: "Bệnh án mới chưa có chuẩn đoán được",
      customField1: null,
      customField2: null,
      customField3: null,
      maBenhNhan: "ATKV01",
      nextStep: null,
      ngay: "2024-02-12T14:58:17.8",
      soLuuTru: "BA002274",
      status: 0,
    },
  ],
  clientCode: "Jairo Rodrigues Peixoto Filho",
  contactName: null,
  email: null,
  note: null,
  openingBalance: null,
  phoneNumber: "0332647971",
  saleInvoices: null,
  tag: null,
  taxCode: null,
};
